name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Trigger Render deployment
      # This tells Render to pull the latest code from your repository.
      - name: Trigger Render deployment
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: srv-d3r1qdripnbc73assl70 # Your Render Service ID
        run: |
          echo "Triggering Render deployment..."
          curl -X POST "https://api.render.com/deploy/srv-${SERVICE_ID}" \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Accept: application/json"